<?php

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

// curl -vvv -H "Authorization: Bearer 3t8D7CeQ3MDn2MLIrx48NQA5JljODRXMBM8iO4PADCI" -X "DELETE" https://www.blockonomics.co/api/button?uid=dac8778e542911eb-acff979c

header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: *");
header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept");

$uid = $_GET["uid"];

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://www.blockonomics.co/api/button?uid=" . $uid);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'DELETE');

$headers = array();
$headers[] = "Authorization: Bearer 3t8D7CeQ3MDn2MLIrx48NQA5JljODRXMBM8iO4PADCI";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    http_response_code(422);
    echo "Error:" . curl_error($ch);
} else {
    http_response_code(200);
    echo "blockonomics deleted:" . $uid . " Result:" . $result;
}
curl_close($ch);

// EMAIL ME RESULTS until fixed
// $myEmail = 'alexandra@powershotz.com';
// $customerEmail = 'test@powershotz.com';
// $subject = 'Delete Child Uid';
// $msg = "Result:" . $result;

// $headers = "MIME-Version: 1.0\r\n";
// $headers .= "Content-type: text/html; charset=UTF-8\r\n";
// $headers .= "From: <" . $customerEmail . ">";

// mail($myEmail, $subject, $msg, $headers);
